module.exports = [
    'HDFC',
    'ICICI',
    'SBI',
    'Citi Bank',
    'Standard Chartered',
    'Standard Chartered',
    'Axis',
    'HSBC',
    'American Express',
    'Federal Bank Limited' ,
    'Punjab National Bank',
    'Bank of India',
    'Bank of Baroda',
    'Andhra Bank',
    'Andhra Bank',
    'Canara Bank',
    'Canara Bank',
    'Indian Bank',
    'Indian Bank',
    'Indian Bank',
    'Barclays Bank',
    'State Bank of Patiala',
    'United Bank of India',
    'Syndicate Bank',
    'Corporation Bank',
    'Central Bank of India',
    'State Bank of Hyderabad',
    'State Bank of Travancore',
    'TATA Credit Card',
    'Kotak Mahindra Bank' ,
    'Indus Ind Bank',
    'RBS (ABN AMRO)',
    'Vijaya Bank',
    'Jammu and Kashmir Bank',
    'Bank of Maharashtra',
    'IDBI',
    'UCO Bank',
    'Karnataka Bank',
    'City Union Bank' ,
    'Yes Bank',
    'Tamilnad Mercantile',
    'South Indian Bank',
    'State Bank of Mysore',
    'State Bank of Bikaner and Jaipur',
    'Oriental Bank of Commerce',
    'Karur Vysya Bank',
    'Karur Vysya Bank',
    'ING Vysya',
    'Indian Overseas Bank',
    'Dena',
    'Allahabad Bank',
    'Deutsche Bank',
    'DBS',
    'Development Credit Bank'
];
